#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# The library defines the full palette; not every wizard uses RED.
# shellcheck disable=SC2034
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret names set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard tells you exactly what to do and checks each step as you\n' "$DIM"
  printf '  go. Close it any time with Ctrl-C and open it again later — it picks\n'
  printf '  up where you left off.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
# ok "..." marks a step done or already satisfied.
ok() { printf '  %s%s✓ %s%s\n' "$BOLD" "$GREEN" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ $reply =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f $ENV_FILE ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && ok "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && ok "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Double-clicked in Finder, the shell starts in $HOME — move to the directory
# this script lives in (the repo root) before anything else.
cd "$(dirname "$0")"
if [[ ! -f flake.nix ]]; then
  warn "Setup.command must live in the repository root (where flake.nix lives)."
  exit 1
fi

banner "First-time setup (macOS)"

# ── Stage 1: your Mac ────────────────────────────────────────────────────
# The wizard's own prerequisites are macOS and git; everything else it
# installs or guides. This stage verifies those two and stops with precise
# instructions when they're missing, so every later stage can assume them.
stage "Your Mac"
if [[ "$(uname -s 2>/dev/null || echo unknown)" != Darwin ]]; then
  warn "This wizard covers macOS only. Setup for Windows and Linux will ship"
  warn "as a separate wizard."
  exit 0
fi
say "macOS detected."
if ! command -v git >/dev/null 2>&1; then
  warn "One of Apple's developer tools is missing. Open the Terminal app, paste"
  warn "this line, and press Enter — macOS shows an install window to click through:"
  note "  xcode-select --install"
  warn "When it finishes, open Setup.command again."
  exit 0
fi
ok "Everything this wizard needs is here. It handles the rest."

# ── Stage 2: Nix ───────────────────────────────────────────────────────────
stage "Install Nix"
if ! command -v nix >/dev/null 2>&1; then
  say "Nix is the only thing this project needs installed on your Mac, and"
  say "Determinate Systems makes a normal Mac installer for it."
  open_url "https://determinate.systems/install/"
  step "On that page, download the macOS installer package."
  step "Open the downloaded file and follow the installer to the end."
  pause "When the installer says it's done, come back here and press Enter."
  # The installer wires up NEW terminals; load Nix into this one too so the
  # wizard can continue in the same window.
  if [[ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
    set +u
    # shellcheck disable=SC1091
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh || true
    set -u
  fi
fi
if command -v nix >/dev/null 2>&1; then
  ok "Nix is installed."
  if [[ -S /nix/var/nix/daemon-socket/socket ]]; then
    say "It's set up the way this project expects."
  else
    warn "Nix is installed, but in a way this project can't fully use — Claude's"
    warn "automated helpers won't be able to build things on their own."
    say "To fix it: uninstall Nix, then re-run this wizard and install it from"
    say "the page it opens."
    note "(Detail for a helper: no daemon socket at /nix/var/nix/daemon-socket/socket.)"
    pause
  fi
else
  warn "Nix isn't ready in this window yet. Double-click Setup.command again —"
  warn "it picks up where you left off."
  exit 0
fi

# ── Stage 3: flakes ────────────────────────────────────────────────────────
stage "Turn on a Nix setting"
# Probe the capability, not the setting: Determinate Nix 3.x ships flakes as
# stable, so 'experimental-features' reads empty there even though flakes work.
_features=$(nix config show experimental-features 2>/dev/null ||
  nix show-config experimental-features 2>/dev/null || true)
if nix eval --expr 'builtins ? getFlake' 2>/dev/null | grep -q '^true$'; then
  ok "Nix is already set up the way this project needs — nothing to change."
elif [[ $_features == *flakes* && $_features == *nix-command* ]]; then
  ok "Nix is already set up the way this project needs — nothing to change."
else
  say "Nix needs one settings line turned on before it can build this project."
  note "(The line: 'experimental-features = nix-command flakes' in ~/.config/nix/nix.conf)"
  if confirm "Add that settings line now?"; then
    mkdir -p "$HOME/.config/nix"
    touch "$HOME/.config/nix/nix.conf"
    if grep -q '^experimental-features' "$HOME/.config/nix/nix.conf"; then
      warn "Your Nix settings file already has a line this wizard won't overwrite."
      warn "Ask for help adding 'nix-command flakes' to it, or edit it yourself:"
      note "  ~/.config/nix/nix.conf"
      pause
    else
      printf 'experimental-features = nix-command flakes\n' >>"$HOME/.config/nix/nix.conf"
      ok "Done — the setting is on."
    fi
  else
    SKIPPED+=("Enable flakes: add 'experimental-features = nix-command flakes' to ~/.config/nix/nix.conf")
    warn "Skipped — the next stages can't work until this is done."
  fi
fi

# ── Stage 4: toolchain ─────────────────────────────────────────────────────
stage "Download the project's tools"
say "Everything this project uses — including Claude Code — comes as one"
say "download, so every machine gets the exact same versions. The Claude app"
say "uses these same tools when you open this folder."
if [[ -e .devshell/bin ]]; then
  ok "The tools are already downloaded — nothing to do."
  note "(If they ever need refreshing: nix build .#toolchain --out-link .devshell)"
elif [[ -t 0 ]]; then
  say "This is the big download — expect several minutes the first time."
  if nix build .#toolchain --out-link .devshell; then
    ok "Tools downloaded."
  else
    warn "The download didn't finish. The usual causes: no internet connection,"
    warn "or the previous stage being skipped. Fix that and open Setup.command again."
    SKIPPED+=("nix build .#toolchain --out-link .devshell")
  fi
else
  note "(Non-interactive run — skipping the download.)"
  SKIPPED+=("nix build .#toolchain --out-link .devshell")
fi

# ── Stage 5: rename on fork (optional) ─────────────────────────────────────
stage "Make it yours: rename the project"
say "The project still carries its placeholder name, 'replaceme'. Give it your"
say "own name now, or skip this if you're only trying things out."
if grep -q '"name": "@replaceme/monorepo"' package.json 2>/dev/null; then
  if confirm "Rename the project now?"; then
    ask NEW_SCOPE "Your organization's short name (lowercase, no spaces — e.g. myorg):"
    NEW_SCOPE=${NEW_SCOPE#@}
    ask NEW_PROJECT "A name for the project itself [press Enter to use the same name]:"
    [[ -z $NEW_PROJECT ]] && NEW_PROJECT="$NEW_SCOPE"
    if [[ -z $NEW_SCOPE ]]; then
      warn "No name given — skipping the rename."
      SKIPPED+=("Rename @replaceme (see README.md for the two manual steps)")
    else
      say "Renaming..."
      grep -rl '@replaceme' --exclude-dir={node_modules,.git,.direnv,dist,.repos,coverage} . |
        while IFS= read -r f; do sed -i '' "s|@replaceme|@${NEW_SCOPE}|g" "$f"; done
      sed -i '' "s|projectName = \"replaceme\"|projectName = \"${NEW_PROJECT}\"|" flake.nix
      ok "Renamed."
    fi
  else
    SKIPPED+=("Rename @replaceme (see README.md for the two manual steps)")
  fi
else
  ok "Already renamed — nothing to do."
fi

# ── Stage 6: git history + reference checkouts (optional) ──────────────────
stage "Keep a history of changes"
if [[ -d .git ]]; then
  ok "This folder already keeps a history of its changes."
  if git config --file .gitmodules --get-regexp path >/dev/null 2>&1 &&
    git ls-files --stage .repos 2>/dev/null | grep -q '^160000'; then
    say ""
    say ".repos/ holds copies of other projects that Claude reads for reference."
    say "Nothing needs them to build — they're an optional download."
    if ! git submodule status 2>/dev/null | grep -q '^-'; then
      ok "They're already downloaded — nothing to do."
    elif confirm "Download them now?"; then
      note "(Runs: git submodule update --init --recursive)"
      git submodule update --init --recursive || warn "The download had trouble; re-run this wizard any time to try again."
    else
      note "Skip is fine — re-run this wizard whenever you want them."
    fi
  fi
else
  say "This folder doesn't keep a history of changes yet — it looks like it"
  say "arrived as a ZIP download."
  say ""
  say "If this project already lives on GitHub and you were invited to it, the"
  say "GitHub stage at the end connects this folder to the team's shared history."
  if confirm "Was this downloaded from a team project that is already on GitHub?"; then
    git init >/dev/null
    ok "History tracking started. The GitHub stage (last one) does the connecting."
  elif confirm "Start keeping a history of changes now? (Recommended — it's how work gets shared and undone safely.)"; then
    git init >/dev/null
    git add -A
    git commit -m "Initial commit from template" >/dev/null
    ok "Done — this folder now keeps its history."
    note "ZIP downloads don't include the .repos/ reference copies; a teammate can"
    note "fetch them later if needed (the two addresses are listed in .gitmodules)."
  else
    SKIPPED+=("Start keeping a history of changes: git init (strongly recommended)")
  fi
fi

# ── Stage 7: dev shell + dependencies ──────────────────────────────────────
stage "Install the project's building blocks"
say "Next, the project downloads the pieces it's built from. Most of it is"
say "already on your Mac from the tools download, so this is quicker."
# pnpm writes .modules.yaml on a successful install; its presence means this
# machine has already been through this stage.
if [[ -f node_modules/.modules.yaml ]]; then
  ok "Already installed — nothing to do."
  note "(If the project's ingredient lists change later, re-run: nix develop -c pnpm install)"
elif [[ -t 0 ]]; then
  say "Installing now — this can take a few minutes."
  note "(Runs: nix develop -c pnpm install)"
  if nix develop -c pnpm install; then
    ok "Building blocks installed."
  else
    warn "That didn't finish. The usual causes: the Nix setting from stage 3 being"
    warn "skipped, or no internet. Fix that and open this wizard again — it skips"
    warn "what's already done."
    SKIPPED+=("nix develop -c pnpm install")
  fi
else
  note "(Non-interactive run — skipping the install.)"
  SKIPPED+=("nix develop -c pnpm install")
fi

# ── Stage 8: smoke check ───────────────────────────────────────────────────
stage "Quick health check"
say "A quick check confirms everything on your Mac fits together."
if [[ -t 0 ]]; then
  say "Checking now — a minute or two."
  note "(Runs: nix develop -c pnpm check)"
  if nix develop -c pnpm check; then
    ok "Everything checks out. Your Mac is ready."
  else
    warn "The check found problems. If you renamed the project in stage 5, the"
    warn "install needs one more pass — open the Claude app and ask it to reinstall"
    warn "and re-check, or show this to a teammate."
    SKIPPED+=("Health check (nix develop -c pnpm install, then nix develop -c pnpm check)")
  fi
else
  note "(Non-interactive run — skipping the check.)"
  SKIPPED+=("nix develop -c pnpm check")
fi

# ── Stage 9: the Claude app ────────────────────────────────────────────────
stage "The Claude app"
say "This project is worked on inside the Claude desktop app: its Code tab is"
say "where you open this folder and ask for changes in plain English."
say ""
# Probe the capability: the app bundle itself. The docs never name the bundle;
# /Applications/Claude.app is what the installer creates today — re-verify on a
# machine with the app if this probe ever misfires.
if [[ -d "/Applications/Claude.app" ]]; then
  ok "The Claude app is already installed — nothing to download."
elif [[ -t 0 ]]; then
  say "It isn't installed yet. The download is a normal Mac installer."
  open_url "https://claude.com/download"
  step "Download the macOS version and open the downloaded file."
  step "Drag Claude into the Applications folder, then open it from there."
  step "Sign in with your Claude account (create one on the same screen if needed)."
  pause "Press Enter once you're signed in."
else
  note "(Non-interactive run — skipping the guided install.)"
  SKIPPED+=("Install the Claude app: https://claude.com/download")
fi
say ""
say "Inside the app, the tab you want is Code. It needs a paid Claude plan"
say "(Pro, Max, Team, or Enterprise) — if the Code tab asks you to upgrade,"
say "the plan is what's missing, not your setup."
step "In the app: Code tab → open this project folder. That's the daily workflow."
if [[ ! -e .devshell/bin ]]; then
  warn "The tools download (stage 4) hasn't happened yet, so the Claude app would"
  warn "be working with the Mac's own, much older tools. Re-run this wizard to"
  warn "finish that first."
fi

# ── Stage 10: GitHub ───────────────────────────────────────────────────────
stage "GitHub"
say "The project's home is a GitHub repository. This stage checks that you can"
say "reach it and that sharing your work with the team will just work."
note "GitHub runs the project's checks automatically — nothing to set up for that."

# gh ships in the pinned toolchain (stage 4); prefer the out-link so this works
# outside a dev shell, falling back to any gh already on PATH.
_gh() {
  if [[ -x .devshell/bin/gh ]]; then
    .devshell/bin/gh "$@"
  elif command -v gh >/dev/null 2>&1; then
    gh "$@"
  else
    return 127
  fi
}

# Reachability probe that never blocks on a credential or host-key prompt.
_can_reach_origin() {
  git remote get-url origin >/dev/null 2>&1 || return 1
  GIT_TERMINAL_PROMPT=0 GIT_SSH_COMMAND="ssh -o BatchMode=yes" \
    git ls-remote --exit-code origin HEAD >/dev/null 2>&1
}

if _can_reach_origin; then
  ok "You can already reach the repository: $(git remote get-url origin)"
  note "When you share work, GitHub checks it automatically."
elif [[ ! -t 0 ]]; then
  note "(Non-interactive run — skipping the guided GitHub setup.)"
  SKIPPED+=("GitHub access: sign in (.devshell/bin/gh auth login --web) and connect the folder")
else
  say ""
  say "Three things make GitHub work: an account, an accepted invitation to the"
  say "repository, and a one-time sign-in so this Mac is allowed to send work up."
  say ""
  if ! confirm "Do you already have a GitHub account?"; then
    open_url "https://github.com/signup"
    step "Create the account (a personal email is fine) and verify the email."
    pause "Press Enter once the account exists."
  fi
  say "A private repository stays invisible until you accept the team's invitation."
  open_url "https://github.com/notifications"
  step "Accept the repository invitation there (it also arrives by email)."
  pause "Press Enter once it's accepted (or if it already was)."
  if ! _gh --version >/dev/null 2>&1; then
    warn "The GitHub sign-in tool comes with the tools download (stage 4), which"
    warn "isn't done yet. Re-run this wizard to finish it, then this stage completes."
    SKIPPED+=("GitHub sign-in (needs the stage-4 tools): .devshell/bin/gh auth login --web")
  elif _gh auth status >/dev/null 2>&1; then
    ok "This Mac is already signed in to GitHub."
  else
    say "Now the one-time sign-in. A browser window opens — approve it there."
    say "When it asks about authenticating Git, answer yes."
    if _gh auth login --hostname github.com --web --git-protocol https; then
      ok "Signed in. From now on this Mac can send and receive the project automatically."
    else
      warn "The sign-in didn't finish; re-run this wizard any time to retry."
      SKIPPED+=("GitHub sign-in: .devshell/bin/gh auth login --web")
    fi
  fi
  say ""
  if git remote get-url origin >/dev/null 2>&1; then
    ok "This folder already points at $(git remote get-url origin)."
    note "When you share work, GitHub checks it automatically."
  elif [[ ! -d .git ]]; then
    warn "This folder isn't keeping a history of changes yet (that stage was"
    warn "skipped), so it can't be connected. Re-run the wizard and say yes there."
    SKIPPED+=("Connect the folder to GitHub (needs the git stage first)")
  elif confirm "Was this folder downloaded from the team's repository (you were invited)?"; then
    step "In the browser, open the repository page — the invitation email links to it."
    step "Click the green 'Code' button and copy the web address it shows (the one starting with https)."
    ask GIT_REMOTE_URL "Paste the repository address:"
    if [[ -n $GIT_REMOTE_URL ]]; then
      git remote add origin "$GIT_REMOTE_URL"
      if git fetch origin; then
        _default_branch=$(git remote show origin 2>/dev/null | sed -n 's/.*HEAD branch: //p')
        [[ -z $_default_branch ]] && _default_branch=main
        if confirm "Link this folder to the team's shared history now? Your files stay as they are."; then
          # Adopt in place: point HEAD at the team's branch, then a mixed reset —
          # it moves the branch and index only and never touches working files.
          git symbolic-ref HEAD "refs/heads/${_default_branch}"
          git reset -q "origin/${_default_branch}"
          git branch --set-upstream-to="origin/${_default_branch}" "$_default_branch" >/dev/null 2>&1 || true
          if [[ -z $(git status --porcelain 2>/dev/null) ]]; then
            ok "Connected — this folder now matches the team's project exactly."
          else
            ok "Connected. A few files differ from the team's copy; the Claude app"
            say "can show you what's different before you share anything."
          fi
          note "(This wizard never pushes for you.)"
        else
          SKIPPED+=("Link the folder to the team's history (re-run this stage)")
        fi
      else
        warn "Couldn't reach the repository. Usual causes: the invitation isn't"
        warn "accepted yet, or the sign-in step above didn't finish."
        git remote remove origin 2>/dev/null || true
        SKIPPED+=("Connect the folder to GitHub (re-run this wizard after accepting the invite)")
      fi
    else
      warn "No address given; re-run this wizard when you have it."
      SKIPPED+=("Connect the folder to GitHub")
    fi
  elif confirm "Create a brand-new GitHub repository for this project instead?"; then
    open_url "https://github.com/new"
    step "Create an empty repository (no README, no license — this project already has files)."
    step "Copy the web address shown in the 'Quick setup' box."
    ask GIT_REMOTE_URL "Paste the repository address:"
    if [[ -n $GIT_REMOTE_URL ]]; then
      git remote add origin "$GIT_REMOTE_URL"
      ok "Connected to your new repository."
      step "When you're ready to send your work up, ask Claude — or run: git push -u origin main"
      note "(This wizard never pushes for you.)"
    else
      warn "No address given; re-run this wizard when you have it."
      SKIPPED+=("Connect the folder to GitHub: git remote add origin <url>")
    fi
  else
    SKIPPED+=("Connect the folder to GitHub (git remote add origin <url>, then push)")
  fi
fi

finish
note "For developers: day-to-day commands are pnpm check / test / lint / build, nix fmt, nix flake check."
note "AGENTS.md is the full technical reference."
