#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# The library defines the full palette; not every wizard uses RED.
# shellcheck disable=SC2034
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret names set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ $reply =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f $ENV_FILE ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Double-clicked in Finder, the shell starts in $HOME — move to the directory
# this script lives in (the repo root) before anything else.
cd "$(dirname "$0")"
if [[ ! -f flake.nix ]]; then
  warn "Setup.command must live in the repository root (where flake.nix lives)."
  exit 1
fi

banner "First-time setup (macOS)"

# ── Stage 1: your Mac ────────────────────────────────────────────────────
# The wizard's own prerequisites are macOS and git; everything else it
# installs or guides. This stage verifies those two and stops with precise
# instructions when they're missing, so every later stage can assume them.
stage "Your Mac"
if [[ "$(uname -s 2>/dev/null || echo unknown)" != Darwin ]]; then
  warn "This wizard covers macOS only. Setup for Windows and Linux will ship"
  warn "as a separate wizard."
  exit 0
fi
say "macOS detected."
if ! command -v git >/dev/null 2>&1; then
  warn "git is missing. Install Apple's command-line tools first:"
  note "  xcode-select --install"
  warn "When that finishes, open Setup.command again."
  exit 0
fi
say "git is available. The wizard handles everything from here."

# ── Stage 2: Nix ───────────────────────────────────────────────────────────
stage "Install Nix"
if ! command -v nix >/dev/null 2>&1; then
  say "Nix is the only thing this project needs installed on your Mac, and"
  say "Determinate Systems makes a normal Mac installer for it."
  open_url "https://determinate.systems/install/"
  step "On that page, download the macOS installer package."
  step "Open the downloaded file and follow the installer to the end."
  pause "When the installer says it's done, come back here and press Enter."
  # The installer wires up NEW terminals; load Nix into this one too so the
  # wizard can continue in the same window.
  if [[ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
    set +u
    # shellcheck disable=SC1091
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh || true
    set -u
  fi
fi
if command -v nix >/dev/null 2>&1; then
  say "Nix is installed."
  if [[ -S /nix/var/nix/daemon-socket/socket ]]; then
    say "Its background service is running — the kind of install this repo expects."
  else
    warn "Nix is installed, but no daemon socket was found at /nix/var/nix/daemon-socket/socket."
    say "This repo's tracked agent sandbox config talks to the daemon socket, so a"
    say "single-user install will work for humans but not for sandboxed agents."
    note "To switch, uninstall and run the Determinate installer instead."
    pause
  fi
else
  warn "Nix isn't visible in this window yet. Open a NEW terminal window, or"
  warn "double-click Setup.command again — it picks up where you left off."
  exit 0
fi

# ── Stage 3: flakes ────────────────────────────────────────────────────────
stage "Enable flakes"
# Probe the capability, not the setting: Determinate Nix 3.x ships flakes as
# stable, so 'experimental-features' reads empty there even though flakes work.
_features=$(nix config show experimental-features 2>/dev/null ||
  nix show-config experimental-features 2>/dev/null || true)
if nix eval --expr 'builtins ? getFlake' 2>/dev/null | grep -q '^true$'; then
  say "Flakes already work on this install — nothing to enable."
elif [[ $_features == *flakes* && $_features == *nix-command* ]]; then
  say "Flakes and the unified 'nix' command are already enabled."
else
  say "This repo is a flake, so Nix needs 'experimental-features = nix-command flakes'."
  if confirm "Add that line to ~/.config/nix/nix.conf now?"; then
    mkdir -p "$HOME/.config/nix"
    touch "$HOME/.config/nix/nix.conf"
    if grep -q '^experimental-features' "$HOME/.config/nix/nix.conf"; then
      warn "Your ~/.config/nix/nix.conf already sets experimental-features; edit it by hand to include: nix-command flakes"
      pause
    else
      printf 'experimental-features = nix-command flakes\n' >>"$HOME/.config/nix/nix.conf"
      say "Enabled in ~/.config/nix/nix.conf."
    fi
  else
    SKIPPED+=("Enable flakes: add 'experimental-features = nix-command flakes' to ~/.config/nix/nix.conf")
    warn "Skipped — later stages will fail until flakes are enabled."
  fi
fi

# ── Stage 4: toolchain ─────────────────────────────────────────────────────
stage "Build the toolchain"
say "Every tool this project uses (Node, pnpm, linters, Claude Code) comes"
say "from Nix, pinned to exact versions. Building the toolchain once downloads"
say "them all — and lets desktop and IDE Claude Code clients use those same"
say "pinned tools when you open this folder."
if [[ -e .devshell/bin ]]; then
  say "The toolchain is already built — nothing to do."
  note "(It survives flake bumps; rebuild with: nix build .#toolchain --out-link .devshell)"
elif [[ -t 0 ]]; then
  say "This is the big download — expect several minutes the first time."
  if nix build .#toolchain --out-link .devshell; then
    say "Toolchain built."
  else
    warn "The build didn't finish. Common causes: no network, or flakes not"
    warn "enabled (previous stage). Fix the cause and open Setup.command again."
    SKIPPED+=("nix build .#toolchain --out-link .devshell")
  fi
else
  note "(Non-interactive run — skipping the build.)"
  SKIPPED+=("nix build .#toolchain --out-link .devshell")
fi

# ── Stage 5: rename on fork (optional) ─────────────────────────────────────
stage "Make it yours: rename @replaceme"
say "The npm scope is the literal placeholder '@replaceme', and the Nix"
say "derivations are named 'replaceme'. Skip this if you're only evaluating."
if grep -q '"name": "@replaceme/monorepo"' package.json 2>/dev/null; then
  if confirm "Rename the project now?"; then
    ask NEW_SCOPE "New npm scope (without the @, e.g. 'myorg'):"
    NEW_SCOPE=${NEW_SCOPE#@}
    ask NEW_PROJECT "Nix project name [default: $NEW_SCOPE]:"
    [[ -z $NEW_PROJECT ]] && NEW_PROJECT="$NEW_SCOPE"
    if [[ -z $NEW_SCOPE ]]; then
      warn "Empty scope — skipping the rename."
      SKIPPED+=("Rename @replaceme (see README.md for the two manual steps)")
    else
      say "Replacing @replaceme with @$NEW_SCOPE across the repo..."
      grep -rl '@replaceme' --exclude-dir={node_modules,.git,.direnv,dist,.repos,coverage} . |
        while IFS= read -r f; do sed -i '' "s|@replaceme|@${NEW_SCOPE}|g" "$f"; done
      say "Setting projectName in flake.nix to \"$NEW_PROJECT\"..."
      sed -i '' "s|projectName = \"replaceme\"|projectName = \"${NEW_PROJECT}\"|" flake.nix
      say "Renamed. (Only the exact placeholder was touched — vendored docs that"
      say "merely contain the word 'replacement' are untouched.)"
    fi
  else
    SKIPPED+=("Rename @replaceme (see README.md for the two manual steps)")
  fi
else
  say "Already renamed — nothing to do."
fi

# ── Stage 6: git history + reference checkouts (optional) ──────────────────
stage "Git repo and reference checkouts"
if [[ -d .git ]]; then
  say "This is already a git repository."
  if git config --file .gitmodules --get-regexp path >/dev/null 2>&1 &&
    git ls-files --stage .repos 2>/dev/null | grep -q '^160000'; then
    say ""
    say ".repos/ holds shallow read-only checkouts coding agents consult as prior"
    say "art. Nothing in the build needs them; they are a download you can skip."
    if ! git submodule status 2>/dev/null | grep -q '^-'; then
      say "They are already fetched — nothing to do."
    elif confirm "Fetch them now (git submodule update --init --recursive)?"; then
      git submodule update --init --recursive || warn "Submodule fetch had trouble; you can re-run it any time."
    else
      note "Skip is fine — re-run the command above whenever you want them."
    fi
  fi
else
  say "No .git directory — you likely downloaded a ZIP."
  say ""
  say "If this project already lives on GitHub and you were invited to it, the"
  say "GitHub stage at the end connects this folder to the team's shared history."
  if confirm "Was this downloaded from a team project that is already on GitHub?"; then
    git init >/dev/null
    say "Version control started. The GitHub stage (last one) does the connecting."
  elif confirm "Initialize a fresh git repository and make an initial commit?"; then
    git init
    git add -A
    git commit -m "Initial commit from template" >/dev/null
    say "Initialized on branch $(git branch --show-current)."
    note "ZIPs don't carry submodules; if you want the .repos/ reference checkouts,"
    note "see .gitmodules for the two URLs and clone them shallowly by hand."
  else
    SKIPPED+=("git init (version control is strongly recommended)")
  fi
fi

# ── Stage 7: dev shell + dependencies ──────────────────────────────────────
stage "Build the dev shell and install dependencies"
say "The first 'nix develop' assembles the dev shell (mostly cached already by"
say "the toolchain build), then pnpm installs the JavaScript dependencies."
# pnpm writes .modules.yaml on a successful install; its presence means this
# machine has already been through this stage.
if [[ -f node_modules/.modules.yaml ]]; then
  say "Dependencies are already installed — nothing to do."
  note "(After editing manifests or catalogs, re-run: nix develop -c pnpm install)"
elif confirm "Run 'nix develop -c pnpm install' now?"; then
  if nix develop -c pnpm install; then
    say "Toolchain built and dependencies installed."
  else
    warn "That didn't finish cleanly. Common causes: flakes not enabled (stage 2),"
    warn "or no network. Fix the cause and re-run this wizard — it will skip ahead."
    SKIPPED+=("nix develop -c pnpm install")
  fi
else
  SKIPPED+=("nix develop -c pnpm install")
fi

# ── Stage 8: smoke check ───────────────────────────────────────────────────
stage "Smoke check"
say "A quick type-check proves the whole graph compiles on your machine."
if confirm "Run 'nix develop -c pnpm check' now?"; then
  if nix develop -c pnpm check; then
    say "Everything compiles. You're set up for development."
  else
    warn "The check didn't pass. If you renamed the scope in stage 5, run"
    warn "'nix develop -c pnpm install' once more and retry; otherwise see AGENTS.md."
    SKIPPED+=("pnpm check (re-run after fixing the cause)")
  fi
else
  SKIPPED+=("pnpm check")
fi

# ── Stage 9: the Claude app ────────────────────────────────────────────────
stage "The Claude app"
say "This project is worked on inside the Claude desktop app: its Code tab is"
say "where you open this folder and ask for changes in plain English."
say ""
# Probe the capability: the app bundle itself. The docs never name the bundle;
# /Applications/Claude.app is what the installer creates today — re-verify on a
# machine with the app if this probe ever misfires.
if [[ -d "/Applications/Claude.app" ]]; then
  say "The Claude app is already installed — nothing to download."
elif [[ -t 0 ]]; then
  say "It isn't installed yet. The download is a normal Mac installer."
  open_url "https://claude.com/download"
  step "Download the macOS version and open the downloaded file."
  step "Drag Claude into the Applications folder, then open it from there."
  step "Sign in with your Claude account (create one on the same screen if needed)."
  pause "Press Enter once you're signed in."
else
  note "(Non-interactive run — skipping the guided install.)"
  SKIPPED+=("Install the Claude app: https://claude.com/download")
fi
say ""
say "Inside the app, the tab you want is Code. It needs a paid Claude plan"
say "(Pro, Max, Team, or Enterprise) — if the Code tab asks you to upgrade,"
say "the plan is what's missing, not your setup."
step "In the app: Code tab → open this project folder. That's the daily workflow."
if [[ ! -e .devshell/bin ]]; then
  warn "The toolchain isn't built yet (stage 4), so the app would fall back to"
  warn "the Mac's own, much older tools. Re-run this wizard to build it first."
fi
note "Prefer a terminal? Run 'nix develop' from this folder, then 'claude' — that"
note "shell pins the version and keeps config and session state inside ./.claude."

# ── Stage 10: GitHub ───────────────────────────────────────────────────────
stage "GitHub"
say "The project's home is a GitHub repository. This stage checks that you can"
say "reach it and that pushing your work will just work."
note "CI (.github/workflows/check.yml) needs no secrets — it runs on its own."

# gh ships in the pinned toolchain (stage 4); prefer the out-link so this works
# outside a dev shell, falling back to any gh already on PATH.
_gh() {
  if [[ -x .devshell/bin/gh ]]; then
    .devshell/bin/gh "$@"
  elif command -v gh >/dev/null 2>&1; then
    gh "$@"
  else
    return 127
  fi
}

# Reachability probe that never blocks on a credential or host-key prompt.
_can_reach_origin() {
  git remote get-url origin >/dev/null 2>&1 || return 1
  GIT_TERMINAL_PROMPT=0 GIT_SSH_COMMAND="ssh -o BatchMode=yes" \
    git ls-remote --exit-code origin HEAD >/dev/null 2>&1
}

if _can_reach_origin; then
  say "You can already reach the repository: $(git remote get-url origin)"
  note "Push when ready; the Check workflow runs on its own."
elif [[ ! -t 0 ]]; then
  note "(Non-interactive run — skipping the guided GitHub setup.)"
  SKIPPED+=("GitHub access: sign in (.devshell/bin/gh auth login --web) and connect the folder")
else
  say ""
  say "Three things make GitHub work: an account, an accepted invitation to the"
  say "repository, and a one-time sign-in on this Mac so pushing is allowed."
  say ""
  if ! confirm "Do you already have a GitHub account?"; then
    open_url "https://github.com/signup"
    step "Create the account (a personal email is fine) and verify the email."
    pause "Press Enter once the account exists."
  fi
  say "A private repository stays invisible until you accept the team's invitation."
  open_url "https://github.com/notifications"
  step "Accept the repository invitation there (it also arrives by email)."
  pause "Press Enter once it's accepted (or if it already was)."
  if ! _gh --version >/dev/null 2>&1; then
    warn "The GitHub sign-in tool ships with the toolchain (stage 4), which isn't"
    warn "built yet. Re-run this wizard to build it, then this stage finishes."
    SKIPPED+=("GitHub sign-in (needs the stage-4 toolchain): .devshell/bin/gh auth login --web")
  elif _gh auth status >/dev/null 2>&1; then
    say "This Mac is already signed in to GitHub."
  else
    say "Now the one-time sign-in. A browser window opens — approve it there."
    say "When it asks about authenticating Git, answer yes."
    if _gh auth login --hostname github.com --web --git-protocol https; then
      say "Signed in. Fetching and pushing use this sign-in automatically from now on."
    else
      warn "The sign-in didn't finish; re-run this wizard any time to retry."
      SKIPPED+=("GitHub sign-in: .devshell/bin/gh auth login --web")
    fi
  fi
  say ""
  if git remote get-url origin >/dev/null 2>&1; then
    say "This folder already points at $(git remote get-url origin)."
    note "Push when ready; the Check workflow runs on its own."
  elif [[ ! -d .git ]]; then
    warn "This folder isn't under version control (the git stage was skipped), so"
    warn "it can't be connected yet. Re-run the wizard and say yes at that stage."
    SKIPPED+=("Connect the folder to GitHub (needs the git stage first)")
  elif confirm "Was this folder downloaded from the team's repository (you were invited)?"; then
    step "In the browser, open the repository page — the invitation email links to it."
    step "Click the green 'Code' button and copy the HTTPS address shown."
    ask GIT_REMOTE_URL "Paste the repository address:"
    if [[ -n $GIT_REMOTE_URL ]]; then
      git remote add origin "$GIT_REMOTE_URL"
      if git fetch origin; then
        _default_branch=$(git remote show origin 2>/dev/null | sed -n 's/.*HEAD branch: //p')
        [[ -z $_default_branch ]] && _default_branch=main
        if confirm "Link this folder to the team's shared history now? Your files stay as they are."; then
          # Adopt in place: point HEAD at the team's branch, then a mixed reset —
          # it moves the branch and index only and never touches working files.
          git symbolic-ref HEAD "refs/heads/${_default_branch}"
          git reset -q "origin/${_default_branch}"
          git branch --set-upstream-to="origin/${_default_branch}" "$_default_branch" >/dev/null 2>&1 || true
          if [[ -z $(git status --porcelain 2>/dev/null) ]]; then
            say "Connected — this folder now matches the team's project exactly."
          else
            say "Connected. A few files differ from the team's copy; the Claude app"
            say "can show you what's different before you share anything."
          fi
          note "(This wizard never pushes for you.)"
        else
          SKIPPED+=("Link the folder to the team's history (re-run this stage)")
        fi
      else
        warn "Couldn't reach the repository. Usual causes: the invitation isn't"
        warn "accepted yet, or the sign-in step above didn't finish."
        git remote remove origin 2>/dev/null || true
        SKIPPED+=("Connect the folder to GitHub (re-run this wizard after accepting the invite)")
      fi
    else
      warn "No address given; re-run this wizard when you have it."
      SKIPPED+=("Connect the folder to GitHub")
    fi
  elif confirm "Create a brand-new GitHub repository for this project instead?"; then
    open_url "https://github.com/new"
    step "Create an empty repository (no README, no license — this repo has files)."
    step "Copy its SSH or HTTPS URL from the 'Quick setup' box."
    ask GIT_REMOTE_URL "Paste the repository URL:"
    if [[ -n $GIT_REMOTE_URL ]]; then
      git remote add origin "$GIT_REMOTE_URL"
      say "Remote 'origin' added."
      step "Push yourself when ready: git push -u origin main"
      note "(This wizard never pushes for you.)"
    else
      warn "No URL given; add it later with: git remote add origin <url>"
      SKIPPED+=("git remote add origin <url>")
    fi
  else
    SKIPPED+=("GitHub remote (git remote add origin <url>, then push)")
  fi
fi

finish
note "Day-to-day commands: pnpm check / test / lint / build, nix fmt, nix flake check."
note "AGENTS.md is the full reference — read it before changing anything structural."
