#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# The library defines the full palette; not every wizard uses RED.
# shellcheck disable=SC2034
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret names set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  {
    if command -v wslview >/dev/null 2>&1; then
      wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then
      explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then
      xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then
      open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ $reply =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f $ENV_FILE ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Run from the repo root: every stage assumes flake.nix is in $PWD.
if [[ ! -f flake.nix ]]; then
  warn "Run this from the repository root (where flake.nix lives)."
  exit 1
fi

# sed -i takes a mandatory '' argument on BSD/macOS and none on GNU.
sed_inplace() {
  if sed --version >/dev/null 2>&1; then sed -i "$@"; else sed -i '' "$@"; fi
}

banner "First-time setup"

# ── Stage 1: platform ────────────────────────────────────────────────────
# The wizard's own prerequisites are a Unix shell and git; everything else it
# installs or guides. This stage verifies those two and stops with precise
# instructions when they're missing, so every later stage can assume them.
stage "Your platform"
case "$(uname -s 2>/dev/null || echo unknown)" in
  Darwin)
    say "macOS detected — fully supported."
    if ! command -v git >/dev/null 2>&1; then
      warn "git is missing. Install Apple's command-line tools first:"
      note "  xcode-select --install"
      warn "When that finishes, re-run this wizard: ./scripts/setup.sh"
      exit 0
    fi
    say "git is available. The wizard handles everything from here."
    ;;
  Linux)
    if grep -qi microsoft /proc/version 2>/dev/null; then
      say "Windows via WSL2 detected — supported, with two things worth checking."
      if [[ -d /run/systemd/system ]]; then
        say "systemd is enabled, so the Nix daemon can run."
      else
        warn "systemd is off in this WSL distro, and the Nix daemon needs it."
        step "Add these two lines to /etc/wsl.conf (sudo needed):"
        note "  [boot]"
        note "  systemd=true"
        step "Then from Windows PowerShell run: wsl --shutdown"
        step "Reopen your WSL terminal and re-run this wizard: ./scripts/setup.sh"
        exit 0
      fi
      if [[ $PWD == /mnt/* ]]; then
        warn "This repo lives on the Windows drive (/mnt/...). Builds there are slow"
        warn "and file watching is unreliable. Consider moving it into the Linux"
        warn "filesystem first, e.g. ~/code/, and re-running from there."
        pause "Press Enter to continue anyway (or Ctrl-C to move it first)."
      fi
    else
      say "Linux detected — fully supported."
    fi
    if ! command -v git >/dev/null 2>&1; then
      warn "git is missing. Install it with your package manager, e.g.:"
      note "  sudo apt install git"
      warn "Then re-run this wizard: ./scripts/setup.sh"
      exit 0
    fi
    say "git is available. The wizard handles everything from here."
    ;;
  MINGW* | MSYS* | CYGWIN*)
    warn "This looks like native Windows (Git Bash or similar). Nix cannot run"
    warn "here — use WSL2, which gives you a real Linux environment inside Windows."
    open_url "https://learn.microsoft.com/windows/wsl/install"
    step "In PowerShell (as Administrator), run: wsl --install"
    step "Reboot, open the Ubuntu app, and clone this repo INSIDE WSL (under ~/,"
    step "not /mnt/c), since builds on the Windows drive are painfully slow."
    step "Then run this wizard again from that WSL terminal."
    exit 0
    ;;
  *)
    warn "Unrecognized platform ($(uname -s 2>/dev/null || echo unknown))."
    warn "macOS, Linux and Windows-via-WSL2 are the tested paths; continuing anyway."
    ;;
esac

# ── Stage 2: Nix ───────────────────────────────────────────────────────────
stage "Install Nix (multi-user)"
if command -v nix >/dev/null 2>&1; then
  say "Nix is already installed."
  if [[ -S /nix/var/nix/daemon-socket/socket ]]; then
    say "The Nix daemon is running — this is the multi-user install this repo expects."
  else
    warn "Nix is installed but no daemon socket was found at /nix/var/nix/daemon-socket/socket."
    say "This repo's tracked agent sandbox config talks to the daemon socket, so a"
    say "single-user install will work for humans but not for sandboxed agents."
    note "To switch, uninstall and re-run the multi-user installer."
    pause
  fi
else
  say "Nix is the only host prerequisite. Install it with a daemon (multi-user)."
  say "Use the Determinate Systems installer — it is the friendliest path: one"
  say "command, flakes enabled out of the box, survives macOS upgrades, and it"
  say "has a clean uninstall. It is also what this repo's CI uses."
  open_url "https://github.com/DeterminateSystems/nix-installer"
  step "Run the install command from that page; it looks like this:"
  note "  curl -fsSL https://install.determinate.systems/nix | sh -s -- install"
  note "(Prefer the standard installer instead? https://nixos.org/download —"
  note " pick 'Multi-user installation'; the next stage helps you enable flakes.)"
  step "When the installer finishes, open a NEW terminal so 'nix' is on your PATH."
  warn "Then re-run this wizard from the new terminal: ./scripts/setup.sh"
  say "It will pick up where you left off."
  exit 0
fi

# ── Stage 3: flakes ────────────────────────────────────────────────────────
stage "Enable flakes"
# Probe the capability, not the setting: Determinate Nix 3.x ships flakes as
# stable, so 'experimental-features' reads empty there even though flakes work.
_features=$(nix config show experimental-features 2>/dev/null ||
  nix show-config experimental-features 2>/dev/null || true)
if nix eval --expr 'builtins ? getFlake' 2>/dev/null | grep -q '^true$'; then
  say "Flakes already work on this install — nothing to enable."
elif [[ $_features == *flakes* && $_features == *nix-command* ]]; then
  say "Flakes and the unified 'nix' command are already enabled."
else
  say "This repo is a flake, so Nix needs 'experimental-features = nix-command flakes'."
  if confirm "Add that line to ~/.config/nix/nix.conf now?"; then
    mkdir -p "$HOME/.config/nix"
    touch "$HOME/.config/nix/nix.conf"
    if grep -q '^experimental-features' "$HOME/.config/nix/nix.conf"; then
      warn "Your ~/.config/nix/nix.conf already sets experimental-features; edit it by hand to include: nix-command flakes"
      pause
    else
      printf 'experimental-features = nix-command flakes\n' >>"$HOME/.config/nix/nix.conf"
      say "Enabled in ~/.config/nix/nix.conf."
    fi
  else
    SKIPPED+=("Enable flakes: add 'experimental-features = nix-command flakes' to ~/.config/nix/nix.conf")
    warn "Skipped — later stages will fail until flakes are enabled."
  fi
fi

# ── Stage 4: direnv (optional) ─────────────────────────────────────────────
stage "direnv (optional, recommended)"
say "direnv drops you into the dev shell automatically whenever you cd into"
say "the repo. Without it you prefix every command with 'nix develop -c'."
if command -v direnv >/dev/null 2>&1; then
  say "direnv is already installed."
  # 'allowed 0' is older direnv's enum for allowed; newer versions say 'true'.
  if direnv status 2>/dev/null | grep -Eq 'Found RC allowed (0|true)'; then
    say "This repo is already allowed — the dev shell loads when you cd in."
  elif confirm "Run 'direnv allow' for this repo now?"; then
    if direnv allow .; then
      say "Allowed — the dev shell loads on your next cd into the repo."
    else
      warn "direnv allow didn't succeed; run it by hand from the repo root."
    fi
  fi
else
  if confirm "Install and set up direnv?"; then
    open_url "https://direnv.net/docs/installation.html"
    step "Install it (e.g. 'nix profile install nixpkgs#direnv' or your package"
    step "manager), then hook it into your shell — for zsh, add to ~/.zshrc:"
    # The hook line must reach ~/.zshrc verbatim, unexpanded.
    # shellcheck disable=SC2016
    note '  eval "$(direnv hook zsh)"'
    step "Open a new terminal, cd back here, and run: direnv allow"
    pause "Done (or noted for later)? Press Enter."
  else
    note "Fine — 'nix develop' gives you the same shell on demand."
  fi
fi

# ── Stage 5: rename on fork (optional) ─────────────────────────────────────
stage "Make it yours: rename @replaceme"
say "The npm scope is the literal placeholder '@replaceme', and the Nix"
say "derivations are named 'replaceme'. Skip this if you're only evaluating."
if grep -q '"name": "@replaceme/monorepo"' package.json 2>/dev/null; then
  if confirm "Rename the project now?"; then
    ask NEW_SCOPE "New npm scope (without the @, e.g. 'myorg'):"
    NEW_SCOPE=${NEW_SCOPE#@}
    ask NEW_PROJECT "Nix project name [default: $NEW_SCOPE]:"
    [[ -z $NEW_PROJECT ]] && NEW_PROJECT="$NEW_SCOPE"
    if [[ -z $NEW_SCOPE ]]; then
      warn "Empty scope — skipping the rename."
      SKIPPED+=("Rename @replaceme (see README.md for the two manual steps)")
    else
      say "Replacing @replaceme with @$NEW_SCOPE across the repo..."
      grep -rl '@replaceme' --exclude-dir={node_modules,.git,.direnv,dist,.repos,coverage} . |
        while IFS= read -r f; do sed_inplace "s|@replaceme|@${NEW_SCOPE}|g" "$f"; done
      say "Setting projectName in flake.nix to \"$NEW_PROJECT\"..."
      sed_inplace "s|projectName = \"replaceme\"|projectName = \"${NEW_PROJECT}\"|" flake.nix
      say "Renamed. (Only the exact placeholder was touched — vendored docs that"
      say "merely contain the word 'replacement' are untouched.)"
    fi
  else
    SKIPPED+=("Rename @replaceme (see README.md for the two manual steps)")
  fi
else
  say "Already renamed — nothing to do."
fi

# ── Stage 6: git history + reference checkouts (optional) ──────────────────
stage "Git repo and reference checkouts"
if [[ -d .git ]]; then
  say "This is already a git repository."
  if git config --file .gitmodules --get-regexp path >/dev/null 2>&1 &&
    git ls-files --stage .repos 2>/dev/null | grep -q '^160000'; then
    say ""
    say ".repos/ holds shallow read-only checkouts coding agents consult as prior"
    say "art. Nothing in the build needs them; they are a download you can skip."
    if ! git submodule status 2>/dev/null | grep -q '^-'; then
      say "They are already fetched — nothing to do."
    elif confirm "Fetch them now (git submodule update --init --recursive)?"; then
      git submodule update --init --recursive || warn "Submodule fetch had trouble; you can re-run it any time."
    else
      note "Skip is fine — re-run the command above whenever you want them."
    fi
  fi
else
  say "No .git directory — you likely downloaded a ZIP."
  if confirm "Initialize a fresh git repository and make an initial commit?"; then
    git init
    git add -A
    git commit -m "Initial commit from template" >/dev/null
    say "Initialized on branch $(git branch --show-current)."
    note "ZIPs don't carry submodules; if you want the .repos/ reference checkouts,"
    note "see .gitmodules for the two URLs and clone them shallowly by hand."
  else
    SKIPPED+=("git init (version control is strongly recommended)")
  fi
fi

# ── Stage 7: dev shell + dependencies ──────────────────────────────────────
stage "Build the dev shell and install dependencies"
say "This is the big one: the first 'nix develop' downloads the whole pinned"
say "toolchain (Node, pnpm, linters, Claude Code), then pnpm installs the"
say "JavaScript dependencies. Expect several minutes on the first run."
# pnpm writes .modules.yaml on a successful install; its presence means this
# machine has already been through this stage.
if [[ -f node_modules/.modules.yaml ]]; then
  say "Dependencies are already installed — nothing to do."
  note "(After editing manifests or catalogs, re-run: nix develop -c pnpm install)"
elif confirm "Run 'nix develop -c pnpm install' now?"; then
  if nix develop -c pnpm install; then
    say "Toolchain built and dependencies installed."
  else
    warn "That didn't finish cleanly. Common causes: flakes not enabled (stage 2),"
    warn "or no network. Fix the cause and re-run this wizard — it will skip ahead."
    SKIPPED+=("nix develop -c pnpm install")
  fi
else
  SKIPPED+=("nix develop -c pnpm install")
fi

# ── Stage 8: smoke check ───────────────────────────────────────────────────
stage "Smoke check"
say "A quick type-check proves the whole graph compiles on your machine."
if confirm "Run 'nix develop -c pnpm check' now?"; then
  if nix develop -c pnpm check; then
    say "Everything compiles. You're set up for development."
  else
    warn "The check didn't pass. If you renamed the scope in stage 4, run"
    warn "'nix develop -c pnpm install' once more and retry; otherwise see AGENTS.md."
    SKIPPED+=("pnpm check (re-run after fixing the cause)")
  fi
else
  SKIPPED+=("pnpm check")
fi

# ── Stage 9: Claude Code ───────────────────────────────────────────────────
stage "Claude Code setup"
say "From a terminal: enter the dev shell (direnv, or 'nix develop') and run"
say "'claude' from the repo root. The shell pins the Claude Code version and"
say "keeps its config and session state inside ./.claude, which already tracks"
say "the sandbox settings and hooks this repo relies on."
say ""
say "Desktop and IDE clients don't inherit the dev shell, so their hooks would"
say "run with the host's ancient bash and BSD tools. Building the toolchain"
say "out-link at ./.devshell fixes that: hook scripts prefer it when present."
if [[ -e .devshell/bin ]]; then
  say "The .devshell out-link is already built — desktop and IDE clients are set."
  note "(It survives flake bumps; rebuild with: nix build .#toolchain --out-link .devshell)"
elif confirm "Build the toolchain out-link now (nix build .#toolchain --out-link .devshell)?"; then
  if nix build .#toolchain --out-link .devshell; then
    say "Built — GUI-launched Claude Code clients now use the pinned tools too."
  else
    warn "Build didn't finish; re-run the command above after fixing the cause."
    SKIPPED+=("nix build .#toolchain --out-link .devshell")
  fi
else
  SKIPPED+=("Toolchain out-link for desktop/IDE Claude Code clients")
fi
note "First launch of 'claude' will walk you through signing in — that part is"
note "between you and Anthropic; no repo config is involved."

# ── Stage 10: GitHub (optional) ────────────────────────────────────────────
stage "GitHub"
say "CI is GitHub Actions (.github/workflows/check.yml). It needs no secrets"
say "or variables — it runs every Nix flake check automatically on push and PR."
if git remote get-url origin >/dev/null 2>&1; then
  say "A remote named 'origin' already exists: $(git remote get-url origin)"
  note "Push when ready; the Check workflow runs on its own."
else
  if confirm "Connect this repo to GitHub now?"; then
    open_url "https://github.com/new"
    step "Create an empty repository (no README, no license — this repo has files)."
    step "Copy its SSH or HTTPS URL from the 'Quick setup' box."
    ask GIT_REMOTE_URL "Paste the repository URL:"
    if [[ -n $GIT_REMOTE_URL ]]; then
      git remote add origin "$GIT_REMOTE_URL"
      say "Remote 'origin' added."
      step "Push yourself when ready: git push -u origin main"
      note "(This wizard never pushes for you.)"
    else
      warn "No URL given; add it later with: git remote add origin <url>"
      SKIPPED+=("git remote add origin <url>")
    fi
  else
    SKIPPED+=("GitHub remote (git remote add origin <url>, then push)")
  fi
fi

finish
note "Day-to-day commands: pnpm check / test / lint / build, nix fmt, nix flake check."
note "AGENTS.md is the full reference — read it before changing anything structural."
